services:
  dbstudio-app:
    image: ibobdb/dbstudio-app:latest
    container_name: dbstudio-app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8083"
    networks:
      - proxy
      - internal
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy:
    external: true
  internal:
    external: true
